server:
  port: 8082

spring:
  application:
    name: first-service

second:
  calculate:
    base-url: http://localhost:8083/second/calculate
    post-computation-url: ${second.calculate.base-url}/finalComputation